### ISSUE TITLE
Show error when renaming database field and name is already taken

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite.Testing#10]
When renaming the Developer "2K Australia" to "2K" when the "2K" entry already exists, it just renames the "2K Australia" entry to just be "2K" as if it's a separate entry.

Something like this would usually combine both entries into a single entry so the program would know they're supposed to be the same piece of metadata. 5.0b still treats them as separate entities even though they shouldn't be.

Certain entered pieces of metadata should be treated more like Unique Names instead of Unique Entries.

**Comment by JosefNemec** [comment]
I have never seen an application to work like you propose, you usually should get an error that the name is already taken. Merging them is definitely a bad idea.

**Comment by DennoCoil** [comment]
https://calibre-ebook.com/

Calibre does it.  I use it all the time.  You rename an author Phil Smith to Phillip Smith and if there's another Phillip Smith, it combines both entries automatically.
