### ISSUE TITLE
New string to replace LOCLibrary in the filters window

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite.Testing#18]
This is more of a request than anything else, but could you add a duplicate of _LOCLibrary_ that would be used specifically for this filter entry ? (it was associated with _LOCLibraries_ in 4.74)

![Sans titre-6](https://user-images.githubusercontent.com/38838369/59384954-ade11980-8d63-11e9-9a36-d86f0c1ad598.jpg)

This would help with the french translation.

**Comment by JosefNemec** [comment]
What's the point of duplicating those string? Why can't you just translate `LOCLibrary`?

**Comment by ClearStrelok** [comment]
It's a really small thing. The LOCLibrary string is also used for this menu entry : 

![Sans titre-14](https://user-images.githubusercontent.com/38838369/59568055-bee89e00-9075-11e9-89a6-c49e5a934757.jpg)

Which was previously named "Tools" (at least using 4.74 with the Modern Skin). 

As mentionned, the "Library" filter used the plural "Libraries" instead, and I had some feedback suggesting that I translate that to the french for "Game Clients", which I did. 

With the new string being used for these two different entries, though, that translation isn't as applicable. Now that I think of it, though, I wouldn't want to bother other translators with that so feel free to close the issue.

**Comment by JosefNemec** [comment]
Yeah this is a problem with translation, it shouldn't translate to "Game Clients".
