### ISSUE TITLE
Option for a "Legacy" cover rendering

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite.Testing#2]
The new way of rendering covers looks very nice with the standardized sizes provided by platforms. The issue is that it doesn't work as well when using external sources such as IGDB, where cover proportions vary wildy even when they mostly adher to the same format. 

This means that pretty much every cover has to be either cropped (which doesn't cooperate well with the low resolution at which IGDB provides the covers) or surrounded by borders. This will get better in a few weeks with new Steam UI and its DVD-type covers hitting public beta test, but It will still look a bit unwieldy for most platforms. In my case, I can't get things to look quite right due to how much variation there is even among DVD-type boxes : 

![Sans titre-1](https://user-images.githubusercontent.com/38838369/59360503-7c9b2600-8d30-11e9-8017-982a83a96c21.jpg)

I'm not sure how feasible this would be inside the current "official" theme, but I think that a toggle for a "locked" grid view that adheres to the way previous versions rendered things (at the cost of the new resizing and spacing options) would be a welcome addition : 

![Sans titre-2](https://user-images.githubusercontent.com/38838369/59360505-7c9b2600-8d30-11e9-9a42-eaefe5205304.jpg)

**Comment by JosefNemec** [comment]
The only difference is that the new system draws background, otherwise the size is the same as the old one if you set the aspect ratio right.
