### ISSUE TITLE
Fullscreen mode: Filter settings not saving when changing tabs.

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite.Testing#20]
I don't know if it's by design or a bug but selected filters get completely cleared to the default state when changing tabs. 

For example, changing settings in the "All" tab and changing to "Most Played" and coming back clears the previously selected filters. I can understand why in certain tabs they get cleared out, but maybe keeping the install status (not only by the option in the settings to keep install only) and platform would be useful to keep across tabs or if by design it works like this, I think at least saving the filters in the "All" tab would be a good option.

**Comment by JosefNemec** [comment]
That's by design. The top options are essentially filter presents (there will be option to add custom ones in future).

Specifically for "Installed" you can go to settings and enable display of installed games only when using those tabs.

**Comment by darklinkpower** [comment]
Gotcha, sounds nice to me.
