### ISSUE TITLE
Fullscreen mode: Battery icon shows 0%

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite.Testing#25]
Battery shows 0% and It also takes from 5 to 10 seconds to update the charging and not charging icons.

![imagen](https://user-images.githubusercontent.com/1389286/59394946-487f2f80-8d47-11e9-90ee-5063753f9975.png)

**Comment by JosefNemec** [comment]
What Windows version? I only have access to battery powered Windows 8 machine and it worked on that :(

**Comment by darklinkpower** [comment]
Oh then it is implemented, I thought it was just a placeholder until it was out of beta and to be implemented.  It's a laptop running windows 10. Forgot to mention it didn't work at any given moment no matter what in the beta.
