### ISSUE TITLE
Fullscreen:  Bad Keyboard and Mouse controls

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite.Testing#27]
I understand it's for a controller, but I don't use one.  There's a lot of problems trying to not use a controller with it.

The ESC key doesn't work.  You can't back out of a menu with the keyboard and there's no place for the mouse to click to back out from.  Arrow keys do not go to every open.  There's no indicator like a rectangular box for keyboard outside of the game select menu.

I consider this a lower priority than fixing the other issues, because if someone is using Keyboard and Mouse, they aren't using a controller when it's recommended for the Fullscreen mode.  To add better keyboard and mouse controls to it, it would need more reworking like adding other indicators and changing things on the fly like switching between a standard\international keyboard and controller on the fly while hiding the mouse cursor when receiving any input from the controller.

**Comment by JosefNemec** [comment]
Backspace is used to back out of menus.

**Comment by JosefNemec** [comment]
Escape now should close all the menus and screens.
