### ISSUE TITLE
Duplicate Game Entries

### ISSUE THREAD

**Issue by Exemplifire** [JosefNemec/Playnite.Testing#28]
I have an issue where I have 2 copies of Mass Effect 2 showing from an Origin Import, even though I only have 1 listed in my Origin client. One is the Deluxe Edition and the other is the regular. Thye both lead to the same install location.

I will say I had EA manually remove the duplicate entry at one point, but I would think that if the game is not showing in Origin any longer it shouldn't show up in Playnite?

I have to say I love this level of customization and I am considering becoming a patron as I find most launchers lack this. But I would like to see if this issue can be resolved?

Otherwise, great work!

**Comment by JosefNemec** [comment]
Once the game is imported it's never automatically removed (this is by design), you have to remove it manually from Playnite.

**Comment by Exemplifire** [comment]
I did. It adds it back on Library update. It appears to be, from what I can tell, detecting Mass Effect 2 from the local Origin Install and the Deluxe Edition from the Origin account and listing them separately even though they both point to the same installation location.

**Comment by JosefNemec** [comment]
I see, then it's the case where Origin likes to duplicate game records in your library (it does that also for trials even if your own the full game). You can hide the duplicate from right-click menu.
