### ISSUE TITLE
Add options for Game Borders (Grid View)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite.Testing#3]
To follow up on #2, I think it would be nice to have some control over the borders that the new version uses when the "Uniform" stretching option is enabled. This could include :

- Opacity
- Color
- Size 

A resizing option in particular would allow the borders to surround the game cover, as so : 

![Sans titre-6](https://user-images.githubusercontent.com/38838369/59364773-b4f23280-8d37-11e9-916f-f3d812008581.jpg)

Instead of only being shown on the horizontal axis : 

![Sans titre-5](https://user-images.githubusercontent.com/38838369/59364791-bb80aa00-8d37-11e9-97c5-15a1a75b17ee.jpg)

I don't think it would mess with the aspect ratio of the cover window either, as the size is increased on both axis. Alternatively, you could set (or add an option for) a fixed vertical border that is alway shown regardless of the cover aspect ratio, the way Launchbox.Next does : 

![Sans titre-3](https://user-images.githubusercontent.com/38838369/59362923-a0606b00-8d34-11e9-9b8b-424ac85c308f.jpg)

**Comment by JosefNemec** [comment]
This IMHO doesn't make sense if you also want to have #2 as you describe. The borders won't be uniform if the source images won't be in the uniform size.
