### ISSUE TITLE
Desktop mode suggestion: Resize images in the description when opening filters

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite.Testing#32]
In the desktop mode there's an issue when opening the filters menu because although it formats the text in the description to the new space, images don't and get cut on the right side. 

without filters:
![imagen](https://user-images.githubusercontent.com/1389286/59611733-7797f700-90e1-11e9-871a-15ff3f87d67e.png)

 with filters:
![imagen](https://user-images.githubusercontent.com/1389286/59611749-854d7c80-90e1-11e9-8b30-a672840d6b2b.png)

with filters and the new explorer panel (I don't know if something could be done here tbh):
![imagen](https://user-images.githubusercontent.com/1389286/59611887-c3e33700-90e1-11e9-8876-b5185340c9f4.png)

**Comment by JosefNemec** [comment]
That's not going to be possible because control we use to render descriptions doesn't support it.
