### ISSUE TITLE
[Beta 2] Games backgrounds are not displayed in Grid view

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite.Testing#40]
![Sans titre-3](https://user-images.githubusercontent.com/38838369/60523109-77574880-9cea-11e9-887b-0250a1e7bcbe.jpg)

**Comment by JosefNemec** [comment]
That's by design for 5.0, you couldn't see majority of the image anyways. It is possible to bring it back via custom theme in future.
