### ISSUE TITLE
Crash when setting the series of multiple games

### ISSUE THREAD

**Issue by kkjdroid** [JosefNemec/Playnite.Testing#41]
a33ab17d-5a0a-40f5-bda6-5a7f21fd12ea  
076d64eb-7536-4fb1-b094-b9ef494d62e9
5a746e7f-f615-4775-8be3-d8d558ca3402
996393d9-6482-4f31-91b7-d5529294ceda
4a44af72-4a8c-4e83-ab15-e0a04002dbaa
9f29eab8-c46d-433a-b86e-04518cbce61d
4c96c150-97d3-486e-80db-34cdbcfb1548
db325a34-ae0c-459c-bf59-883917b7a803

Happens sporadically when creating a new series and assigning multiple games to it.

**Comment by JosefNemec** [comment]
Please report beta build issues to [Playnite.Testing](https://github.com/JosefNemec/Playnite.Testing) repository as wiki states. Thank you
