### ISSUE TITLE
Opacity option

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite.Testing#6]
I'm under the assumption that the main windows all use the same opacity factor : 

![Sans titre-11](https://user-images.githubusercontent.com/38838369/59371236-b7a75480-8d44-11e9-8542-76bab9510a20.jpg)

If that is indeed the case, it would be nice to allow users control over the general opacity of transparents windows. While this is something that themes could take care of, I feel this would be better off not being dependant of wathever theme you're using.

**Comment by JosefNemec** [comment]
This will be obsolete in the final 5.0, the background will not be stretched thought the whole window (if you open several panels you can't see majority of it anyways). Current 4.7 look will be added as legacy option.
