### ISSUE TITLE
Twitch integration doesn't work

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite.Testing#9]
Twitch integration doesn’t work for some reason.  Can’t authenticate and there’s no error except “User is not logged in.”

It's strange because I do have the correct information, but it could be broken on Twitch's end because even their official app on my Windows 7 install doesn't output properly.  Could be the firewall as well since I've blocked all Windows\Microsoft oriented connections.

**Comment by DennoCoil** [comment]
Just to add more, there are several people in the Discord server that have said the same thing.  So it's not just me, but either Twitch or the way Playnite handles Twitch shows the authentication thing is broken.

**Comment by maybenikhil** [comment]
Twitch has been broken for a *long* time, so I wouldn't say that it is top priority

**Comment by JosefNemec** [comment]
This is not a beta only issue.
